name: Deploy Squall

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/th1er/malebolge/Rainbow
            git pull origin develop
            docker exec male-rainbow nginx -s reload

      - name: Healthcheck
        run: |
          echo "Deploy concluído."
          echo "Verifique: https://rapsodia.th1eros.dev"